spring:
  security:
    oauth2:
      client:
        registration:
          salesforce:
            client-id: 3MVG91oqviqJKoEHCwtJa0_YA_2YVHxnK3qzAUph5dY_SF_0T7OIFNVT9f4AeT5z.wKfE9LRtEkchqFnENWut
            client-secret: 2256CDC0420AC3DF9778266C91A5FF0D5473C210FADD1E31D32B9FAB100294A5
            scope: openid
            authorization-grant-type: client_credentials
            redirect-uri: "{baseUrl}/callback"
        provider:
            salesforce:
              authorization-uri: https://login.salesforce.com/services/oauth2/authorize
              token-uri: https://login.salesforce.com/services/oauth2/token
              user-info-uri: https://login.salesforce.com/services/oauth2/userinfo
  #data.redis.host: localhost
  #data.redis.password: your_redis_password
  #data.redis.port: 6379
#kms:
#  provider: AWS # or any other KMS service
#  key-id: 02100112-2443-4e6b-bf39-ecd539f1856c #your_kms_key_id
aws:
   accessKeyId: ASIASVLKCTHWKM2LQCKY
   secretAccessKey: s6j+VzmNDmPmDDfQXAeuWnWC+GexmKzEZCMC19rv
   region: us-east-1
   alias: dmacs-demo
   profile: kms-user-profile
management:
 endpoints:
    web:
      exposure:
        include: health,info
        exclude: env,beans,heapdump
server:
     port: 443 # Port for HTTPS, default is 8443
     ssl:
        enabled: true
        key-store: file:/home/med.ds.osd.mil/sanjeev.mehrotra.sa/workspace/sw/byok.0/byok/certs/certsHFNBYOKSRV.jks
        key-store-password: changeit
        key-store-type: PKCS12
        key-alias: hfnbyok-cert
        enabled-protocols: TLSv1.2
     tomcat:
         max-threads: 200
         min-spare-threads: 10
         accept-count: 100
         max-swallow-size: 2MB
         max-http-post-size: 2MB
         accesslog:
               enabled: true
               directory: logs
               file-date-format: yyyy-MM-dd
               prefix: access_log
               suffix: .log
     #address: localhost #makes server more selective and does not allow connetions from all IPV4 address
     error:
         whitelabel:
               enabled: false
         include-exception: true
         include-stacktrace: never
     connection-timeout: 5s
     max-http-header-size: 8KB

springdoc:
   api-dcos:
   path: /api-docs
spring.ssl.bundle.pem:
  demo:
    reload-on-update: true
    keystore:
      certificate: "certs/demo.crt"
      private-key: "certs/demo.key"
logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: /opt/dmacs/logs/archived/application-%d{yyyy-MM-dd}.%i.log
      max-history: 30
  file:
   name: /opt/dmacs/logs/application.log
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %-5level [%thread] %logger : %msg%n"
    level: "%5p"
  level:
    root: INFO
    org.springframework.web: DEBUG
    mil.dod.dha.byok: INFO
    mil.dod.dha.byok.services: DEBUG
    mil.dod.dha.byok.utils.BearerTokenUtilities: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    rector.netty.http.client: DEBUG
salesforce:
    base-url: https://militaryhealth--hfnbyok.develop.my.salesforce.com
    username: sanjeev.mehrotra.ctr@health.mil
    password: C0mpl\!@nce5862\! 
    consumer-secret: 2256CDC0420AC3DF9778266C91A5FF0D5473C210FADD1E31D32B9FAB100294A5
    consumer-key: 3MVG91oqviqJKoEHCwtJa0_YA_2YVHxnK3qzAUph5dY_SF_0T7OIFNVT9f4AeT5z.wKfE9LRtEkchqFnENWut
dmacs:
    app:
       setting: $HOME/dmacs.properties
    config:
       path: $HOME/dmacs.properties

